package com.scnu.o2o.domain;

import java.util.Date;

public class Award {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_award.award_id
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private Integer awardId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_award.award_name
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private String awardName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_award.award_desc
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private String awardDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_award.award_img
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private String awardImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_award.point
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private Integer point;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_award.priority
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private Integer priority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_award.create_time
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_award.expire_time
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private Date expireTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_award.last_edit_time
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private Date lastEditTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_award.enable_status
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private Integer enableStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_award.shop_id
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private Integer shopId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_award.award_id
     *
     * @return the value of tb_award.award_id
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public Integer getAwardId() {
        return awardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_award.award_id
     *
     * @param awardId the value for tb_award.award_id
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setAwardId(Integer awardId) {
        this.awardId = awardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_award.award_name
     *
     * @return the value of tb_award.award_name
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public String getAwardName() {
        return awardName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_award.award_name
     *
     * @param awardName the value for tb_award.award_name
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setAwardName(String awardName) {
        this.awardName = awardName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_award.award_desc
     *
     * @return the value of tb_award.award_desc
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public String getAwardDesc() {
        return awardDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_award.award_desc
     *
     * @param awardDesc the value for tb_award.award_desc
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setAwardDesc(String awardDesc) {
        this.awardDesc = awardDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_award.award_img
     *
     * @return the value of tb_award.award_img
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public String getAwardImg() {
        return awardImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_award.award_img
     *
     * @param awardImg the value for tb_award.award_img
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setAwardImg(String awardImg) {
        this.awardImg = awardImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_award.point
     *
     * @return the value of tb_award.point
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public Integer getPoint() {
        return point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_award.point
     *
     * @param point the value for tb_award.point
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setPoint(Integer point) {
        this.point = point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_award.priority
     *
     * @return the value of tb_award.priority
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_award.priority
     *
     * @param priority the value for tb_award.priority
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_award.create_time
     *
     * @return the value of tb_award.create_time
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_award.create_time
     *
     * @param createTime the value for tb_award.create_time
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_award.expire_time
     *
     * @return the value of tb_award.expire_time
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public Date getExpireTime() {
        return expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_award.expire_time
     *
     * @param expireTime the value for tb_award.expire_time
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setExpireTime(Date expireTime) {
        this.expireTime = expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_award.last_edit_time
     *
     * @return the value of tb_award.last_edit_time
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public Date getLastEditTime() {
        return lastEditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_award.last_edit_time
     *
     * @param lastEditTime the value for tb_award.last_edit_time
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setLastEditTime(Date lastEditTime) {
        this.lastEditTime = lastEditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_award.enable_status
     *
     * @return the value of tb_award.enable_status
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public Integer getEnableStatus() {
        return enableStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_award.enable_status
     *
     * @param enableStatus the value for tb_award.enable_status
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setEnableStatus(Integer enableStatus) {
        this.enableStatus = enableStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_award.shop_id
     *
     * @return the value of tb_award.shop_id
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public Integer getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_award.shop_id
     *
     * @param shopId the value for tb_award.shop_id
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setShopId(Integer shopId) {
        this.shopId = shopId;
    }
}