package com.scnu.o2o.domain;

import java.util.Date;

public class HeadLine {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_head_line.line_id
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private Integer lineId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_head_line.line_name
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private String lineName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_head_line.line_link
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private String lineLink;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_head_line.line_img
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private String lineImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_head_line.priority
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private Integer priority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_head_line.enable_status
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private Integer enableStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_head_line.create_time
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_head_line.last_edit_time
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private Date lastEditTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_head_line.line_id
     *
     * @return the value of tb_head_line.line_id
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public Integer getLineId() {
        return lineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_head_line.line_id
     *
     * @param lineId the value for tb_head_line.line_id
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setLineId(Integer lineId) {
        this.lineId = lineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_head_line.line_name
     *
     * @return the value of tb_head_line.line_name
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public String getLineName() {
        return lineName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_head_line.line_name
     *
     * @param lineName the value for tb_head_line.line_name
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setLineName(String lineName) {
        this.lineName = lineName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_head_line.line_link
     *
     * @return the value of tb_head_line.line_link
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public String getLineLink() {
        return lineLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_head_line.line_link
     *
     * @param lineLink the value for tb_head_line.line_link
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setLineLink(String lineLink) {
        this.lineLink = lineLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_head_line.line_img
     *
     * @return the value of tb_head_line.line_img
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public String getLineImg() {
        return lineImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_head_line.line_img
     *
     * @param lineImg the value for tb_head_line.line_img
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setLineImg(String lineImg) {
        this.lineImg = lineImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_head_line.priority
     *
     * @return the value of tb_head_line.priority
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_head_line.priority
     *
     * @param priority the value for tb_head_line.priority
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_head_line.enable_status
     *
     * @return the value of tb_head_line.enable_status
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public Integer getEnableStatus() {
        return enableStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_head_line.enable_status
     *
     * @param enableStatus the value for tb_head_line.enable_status
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setEnableStatus(Integer enableStatus) {
        this.enableStatus = enableStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_head_line.create_time
     *
     * @return the value of tb_head_line.create_time
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_head_line.create_time
     *
     * @param createTime the value for tb_head_line.create_time
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_head_line.last_edit_time
     *
     * @return the value of tb_head_line.last_edit_time
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public Date getLastEditTime() {
        return lastEditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_head_line.last_edit_time
     *
     * @param lastEditTime the value for tb_head_line.last_edit_time
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setLastEditTime(Date lastEditTime) {
        this.lastEditTime = lastEditTime;
    }
}