package com.scnu.o2o.domain;

import java.util.Date;

public class PersonInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_person_info.user_id
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_person_info.name
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_person_info.birthday
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_person_info.gender
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_person_info.phone
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_person_info.email
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_person_info.profile_img
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private String profileImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_person_info.customer_flag
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private Integer customerFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_person_info.shop_owner_flag
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private Integer shopOwnerFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_person_info.admin_flag
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private Integer adminFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_person_info.create_time
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_person_info.last_edit_time
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private Date lastEditTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_person_info.enable_status
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private Integer enableStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_person_info.user_id
     *
     * @return the value of tb_person_info.user_id
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_person_info.user_id
     *
     * @param userId the value for tb_person_info.user_id
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_person_info.name
     *
     * @return the value of tb_person_info.name
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_person_info.name
     *
     * @param name the value for tb_person_info.name
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_person_info.birthday
     *
     * @return the value of tb_person_info.birthday
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_person_info.birthday
     *
     * @param birthday the value for tb_person_info.birthday
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_person_info.gender
     *
     * @return the value of tb_person_info.gender
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_person_info.gender
     *
     * @param gender the value for tb_person_info.gender
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setGender(String gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_person_info.phone
     *
     * @return the value of tb_person_info.phone
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_person_info.phone
     *
     * @param phone the value for tb_person_info.phone
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_person_info.email
     *
     * @return the value of tb_person_info.email
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_person_info.email
     *
     * @param email the value for tb_person_info.email
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_person_info.profile_img
     *
     * @return the value of tb_person_info.profile_img
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public String getProfileImg() {
        return profileImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_person_info.profile_img
     *
     * @param profileImg the value for tb_person_info.profile_img
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setProfileImg(String profileImg) {
        this.profileImg = profileImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_person_info.customer_flag
     *
     * @return the value of tb_person_info.customer_flag
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public Integer getCustomerFlag() {
        return customerFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_person_info.customer_flag
     *
     * @param customerFlag the value for tb_person_info.customer_flag
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setCustomerFlag(Integer customerFlag) {
        this.customerFlag = customerFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_person_info.shop_owner_flag
     *
     * @return the value of tb_person_info.shop_owner_flag
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public Integer getShopOwnerFlag() {
        return shopOwnerFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_person_info.shop_owner_flag
     *
     * @param shopOwnerFlag the value for tb_person_info.shop_owner_flag
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setShopOwnerFlag(Integer shopOwnerFlag) {
        this.shopOwnerFlag = shopOwnerFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_person_info.admin_flag
     *
     * @return the value of tb_person_info.admin_flag
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public Integer getAdminFlag() {
        return adminFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_person_info.admin_flag
     *
     * @param adminFlag the value for tb_person_info.admin_flag
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setAdminFlag(Integer adminFlag) {
        this.adminFlag = adminFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_person_info.create_time
     *
     * @return the value of tb_person_info.create_time
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_person_info.create_time
     *
     * @param createTime the value for tb_person_info.create_time
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_person_info.last_edit_time
     *
     * @return the value of tb_person_info.last_edit_time
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public Date getLastEditTime() {
        return lastEditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_person_info.last_edit_time
     *
     * @param lastEditTime the value for tb_person_info.last_edit_time
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setLastEditTime(Date lastEditTime) {
        this.lastEditTime = lastEditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_person_info.enable_status
     *
     * @return the value of tb_person_info.enable_status
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public Integer getEnableStatus() {
        return enableStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_person_info.enable_status
     *
     * @param enableStatus the value for tb_person_info.enable_status
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setEnableStatus(Integer enableStatus) {
        this.enableStatus = enableStatus;
    }
}