package com.scnu.o2o.domain;

import java.util.Date;

public class ProductImg {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product_img.product_img_id
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private Integer productImgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product_img.img_addr
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private String imgAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product_img.img_desc
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private String imgDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product_img.priority
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private Integer priority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product_img.create_time
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product_img.product_id
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private Integer productId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product_img.product_img_id
     *
     * @return the value of tb_product_img.product_img_id
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public Integer getProductImgId() {
        return productImgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product_img.product_img_id
     *
     * @param productImgId the value for tb_product_img.product_img_id
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setProductImgId(Integer productImgId) {
        this.productImgId = productImgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product_img.img_addr
     *
     * @return the value of tb_product_img.img_addr
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public String getImgAddr() {
        return imgAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product_img.img_addr
     *
     * @param imgAddr the value for tb_product_img.img_addr
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setImgAddr(String imgAddr) {
        this.imgAddr = imgAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product_img.img_desc
     *
     * @return the value of tb_product_img.img_desc
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public String getImgDesc() {
        return imgDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product_img.img_desc
     *
     * @param imgDesc the value for tb_product_img.img_desc
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setImgDesc(String imgDesc) {
        this.imgDesc = imgDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product_img.priority
     *
     * @return the value of tb_product_img.priority
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product_img.priority
     *
     * @param priority the value for tb_product_img.priority
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product_img.create_time
     *
     * @return the value of tb_product_img.create_time
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product_img.create_time
     *
     * @param createTime the value for tb_product_img.create_time
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product_img.product_id
     *
     * @return the value of tb_product_img.product_id
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product_img.product_id
     *
     * @param productId the value for tb_product_img.product_id
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }
}