package com.scnu.o2o.domain;

import java.util.Date;

public class ProductCategory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product_category.product_category_id
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private Integer productCategoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product_category.product_category_name
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private String productCategoryName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product_category.product_category_desc
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private String productCategoryDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product_category.priority
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private Integer priority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product_category.create_time
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product_category.last_edit_time
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private Date lastEditTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product_category.shop_id
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private Integer shopId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product_category.product_category_id
     *
     * @return the value of tb_product_category.product_category_id
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public Integer getProductCategoryId() {
        return productCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product_category.product_category_id
     *
     * @param productCategoryId the value for tb_product_category.product_category_id
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setProductCategoryId(Integer productCategoryId) {
        this.productCategoryId = productCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product_category.product_category_name
     *
     * @return the value of tb_product_category.product_category_name
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public String getProductCategoryName() {
        return productCategoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product_category.product_category_name
     *
     * @param productCategoryName the value for tb_product_category.product_category_name
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setProductCategoryName(String productCategoryName) {
        this.productCategoryName = productCategoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product_category.product_category_desc
     *
     * @return the value of tb_product_category.product_category_desc
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public String getProductCategoryDesc() {
        return productCategoryDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product_category.product_category_desc
     *
     * @param productCategoryDesc the value for tb_product_category.product_category_desc
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setProductCategoryDesc(String productCategoryDesc) {
        this.productCategoryDesc = productCategoryDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product_category.priority
     *
     * @return the value of tb_product_category.priority
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product_category.priority
     *
     * @param priority the value for tb_product_category.priority
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product_category.create_time
     *
     * @return the value of tb_product_category.create_time
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product_category.create_time
     *
     * @param createTime the value for tb_product_category.create_time
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product_category.last_edit_time
     *
     * @return the value of tb_product_category.last_edit_time
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public Date getLastEditTime() {
        return lastEditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product_category.last_edit_time
     *
     * @param lastEditTime the value for tb_product_category.last_edit_time
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setLastEditTime(Date lastEditTime) {
        this.lastEditTime = lastEditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product_category.shop_id
     *
     * @return the value of tb_product_category.shop_id
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public Integer getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product_category.shop_id
     *
     * @param shopId the value for tb_product_category.shop_id
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setShopId(Integer shopId) {
        this.shopId = shopId;
    }
}