package com.scnu.o2o.domain;

import java.util.Date;

public class Product {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product.product_id
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private Integer productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product.product_name
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product.product_desc
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private String productDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product.img_addr
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private String imgAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product.normal_price
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private String normalPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product.promotion_price
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private String promotionPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product.priority
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private Integer priority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product.create_time
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product.last_edit_time
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private Date lastEditTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product.enable_status
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private Integer enableStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product.point
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private Integer point;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product.product_category_id
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private Integer productCategoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product.shop_id
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private Integer shopId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product.product_id
     *
     * @return the value of tb_product.product_id
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product.product_id
     *
     * @param productId the value for tb_product.product_id
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product.product_name
     *
     * @return the value of tb_product.product_name
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product.product_name
     *
     * @param productName the value for tb_product.product_name
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setProductName(String productName) {
        this.productName = productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product.product_desc
     *
     * @return the value of tb_product.product_desc
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public String getProductDesc() {
        return productDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product.product_desc
     *
     * @param productDesc the value for tb_product.product_desc
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setProductDesc(String productDesc) {
        this.productDesc = productDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product.img_addr
     *
     * @return the value of tb_product.img_addr
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public String getImgAddr() {
        return imgAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product.img_addr
     *
     * @param imgAddr the value for tb_product.img_addr
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setImgAddr(String imgAddr) {
        this.imgAddr = imgAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product.normal_price
     *
     * @return the value of tb_product.normal_price
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public String getNormalPrice() {
        return normalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product.normal_price
     *
     * @param normalPrice the value for tb_product.normal_price
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setNormalPrice(String normalPrice) {
        this.normalPrice = normalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product.promotion_price
     *
     * @return the value of tb_product.promotion_price
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public String getPromotionPrice() {
        return promotionPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product.promotion_price
     *
     * @param promotionPrice the value for tb_product.promotion_price
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setPromotionPrice(String promotionPrice) {
        this.promotionPrice = promotionPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product.priority
     *
     * @return the value of tb_product.priority
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product.priority
     *
     * @param priority the value for tb_product.priority
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product.create_time
     *
     * @return the value of tb_product.create_time
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product.create_time
     *
     * @param createTime the value for tb_product.create_time
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product.last_edit_time
     *
     * @return the value of tb_product.last_edit_time
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public Date getLastEditTime() {
        return lastEditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product.last_edit_time
     *
     * @param lastEditTime the value for tb_product.last_edit_time
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setLastEditTime(Date lastEditTime) {
        this.lastEditTime = lastEditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product.enable_status
     *
     * @return the value of tb_product.enable_status
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public Integer getEnableStatus() {
        return enableStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product.enable_status
     *
     * @param enableStatus the value for tb_product.enable_status
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setEnableStatus(Integer enableStatus) {
        this.enableStatus = enableStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product.point
     *
     * @return the value of tb_product.point
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public Integer getPoint() {
        return point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product.point
     *
     * @param point the value for tb_product.point
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setPoint(Integer point) {
        this.point = point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product.product_category_id
     *
     * @return the value of tb_product.product_category_id
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public Integer getProductCategoryId() {
        return productCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product.product_category_id
     *
     * @param productCategoryId the value for tb_product.product_category_id
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setProductCategoryId(Integer productCategoryId) {
        this.productCategoryId = productCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product.shop_id
     *
     * @return the value of tb_product.shop_id
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public Integer getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product.shop_id
     *
     * @param shopId the value for tb_product.shop_id
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setShopId(Integer shopId) {
        this.shopId = shopId;
    }
}