package com.scnu.o2o.domain;

import java.util.Date;

public class Shop {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shop.shop_id
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private Integer shopId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shop.owner_id
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private Integer ownerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shop.area_id
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private Integer areaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shop.shop_category_id
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private Integer shopCategoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shop.parent_category_id
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private Integer parentCategoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shop.shop_name
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private String shopName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shop.shop_desc
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private String shopDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shop.shop_addr
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private String shopAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shop.phone
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shop.shop_img
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private String shopImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shop.longitude
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private Double longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shop.latitude
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private Double latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shop.priority
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private Integer priority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shop.create_time
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shop.last_edit_time
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private Date lastEditTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shop.enable_status
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private Integer enableStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shop.advice
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private String advice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_shop.shop_id
     *
     * @return the value of tb_shop.shop_id
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public Integer getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_shop.shop_id
     *
     * @param shopId the value for tb_shop.shop_id
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setShopId(Integer shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_shop.owner_id
     *
     * @return the value of tb_shop.owner_id
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public Integer getOwnerId() {
        return ownerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_shop.owner_id
     *
     * @param ownerId the value for tb_shop.owner_id
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setOwnerId(Integer ownerId) {
        this.ownerId = ownerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_shop.area_id
     *
     * @return the value of tb_shop.area_id
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public Integer getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_shop.area_id
     *
     * @param areaId the value for tb_shop.area_id
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setAreaId(Integer areaId) {
        this.areaId = areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_shop.shop_category_id
     *
     * @return the value of tb_shop.shop_category_id
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public Integer getShopCategoryId() {
        return shopCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_shop.shop_category_id
     *
     * @param shopCategoryId the value for tb_shop.shop_category_id
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setShopCategoryId(Integer shopCategoryId) {
        this.shopCategoryId = shopCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_shop.parent_category_id
     *
     * @return the value of tb_shop.parent_category_id
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public Integer getParentCategoryId() {
        return parentCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_shop.parent_category_id
     *
     * @param parentCategoryId the value for tb_shop.parent_category_id
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setParentCategoryId(Integer parentCategoryId) {
        this.parentCategoryId = parentCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_shop.shop_name
     *
     * @return the value of tb_shop.shop_name
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public String getShopName() {
        return shopName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_shop.shop_name
     *
     * @param shopName the value for tb_shop.shop_name
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setShopName(String shopName) {
        this.shopName = shopName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_shop.shop_desc
     *
     * @return the value of tb_shop.shop_desc
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public String getShopDesc() {
        return shopDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_shop.shop_desc
     *
     * @param shopDesc the value for tb_shop.shop_desc
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setShopDesc(String shopDesc) {
        this.shopDesc = shopDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_shop.shop_addr
     *
     * @return the value of tb_shop.shop_addr
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public String getShopAddr() {
        return shopAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_shop.shop_addr
     *
     * @param shopAddr the value for tb_shop.shop_addr
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setShopAddr(String shopAddr) {
        this.shopAddr = shopAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_shop.phone
     *
     * @return the value of tb_shop.phone
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_shop.phone
     *
     * @param phone the value for tb_shop.phone
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_shop.shop_img
     *
     * @return the value of tb_shop.shop_img
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public String getShopImg() {
        return shopImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_shop.shop_img
     *
     * @param shopImg the value for tb_shop.shop_img
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setShopImg(String shopImg) {
        this.shopImg = shopImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_shop.longitude
     *
     * @return the value of tb_shop.longitude
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public Double getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_shop.longitude
     *
     * @param longitude the value for tb_shop.longitude
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_shop.latitude
     *
     * @return the value of tb_shop.latitude
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public Double getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_shop.latitude
     *
     * @param latitude the value for tb_shop.latitude
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_shop.priority
     *
     * @return the value of tb_shop.priority
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_shop.priority
     *
     * @param priority the value for tb_shop.priority
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_shop.create_time
     *
     * @return the value of tb_shop.create_time
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_shop.create_time
     *
     * @param createTime the value for tb_shop.create_time
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_shop.last_edit_time
     *
     * @return the value of tb_shop.last_edit_time
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public Date getLastEditTime() {
        return lastEditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_shop.last_edit_time
     *
     * @param lastEditTime the value for tb_shop.last_edit_time
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setLastEditTime(Date lastEditTime) {
        this.lastEditTime = lastEditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_shop.enable_status
     *
     * @return the value of tb_shop.enable_status
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public Integer getEnableStatus() {
        return enableStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_shop.enable_status
     *
     * @param enableStatus the value for tb_shop.enable_status
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setEnableStatus(Integer enableStatus) {
        this.enableStatus = enableStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_shop.advice
     *
     * @return the value of tb_shop.advice
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public String getAdvice() {
        return advice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_shop.advice
     *
     * @param advice the value for tb_shop.advice
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setAdvice(String advice) {
        this.advice = advice;
    }
}