package com.scnu.o2o.domain;

import java.util.Date;

public class ShopAuthMap {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shop_auth_map.shop_auth_id
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private Integer shopAuthId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shop_auth_map.employee_id
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private Integer employeeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shop_auth_map.shop_id
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private Integer shopId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shop_auth_map.name
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shop_auth_map.title
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shop_auth_map.title_flag
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private Integer titleFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shop_auth_map.create_time
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shop_auth_map.last_edit_time
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private Date lastEditTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shop_auth_map.enable_status
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private Integer enableStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_shop_auth_map.shop_auth_id
     *
     * @return the value of tb_shop_auth_map.shop_auth_id
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public Integer getShopAuthId() {
        return shopAuthId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_shop_auth_map.shop_auth_id
     *
     * @param shopAuthId the value for tb_shop_auth_map.shop_auth_id
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setShopAuthId(Integer shopAuthId) {
        this.shopAuthId = shopAuthId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_shop_auth_map.employee_id
     *
     * @return the value of tb_shop_auth_map.employee_id
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public Integer getEmployeeId() {
        return employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_shop_auth_map.employee_id
     *
     * @param employeeId the value for tb_shop_auth_map.employee_id
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setEmployeeId(Integer employeeId) {
        this.employeeId = employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_shop_auth_map.shop_id
     *
     * @return the value of tb_shop_auth_map.shop_id
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public Integer getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_shop_auth_map.shop_id
     *
     * @param shopId the value for tb_shop_auth_map.shop_id
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setShopId(Integer shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_shop_auth_map.name
     *
     * @return the value of tb_shop_auth_map.name
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_shop_auth_map.name
     *
     * @param name the value for tb_shop_auth_map.name
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_shop_auth_map.title
     *
     * @return the value of tb_shop_auth_map.title
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_shop_auth_map.title
     *
     * @param title the value for tb_shop_auth_map.title
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_shop_auth_map.title_flag
     *
     * @return the value of tb_shop_auth_map.title_flag
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public Integer getTitleFlag() {
        return titleFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_shop_auth_map.title_flag
     *
     * @param titleFlag the value for tb_shop_auth_map.title_flag
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setTitleFlag(Integer titleFlag) {
        this.titleFlag = titleFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_shop_auth_map.create_time
     *
     * @return the value of tb_shop_auth_map.create_time
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_shop_auth_map.create_time
     *
     * @param createTime the value for tb_shop_auth_map.create_time
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_shop_auth_map.last_edit_time
     *
     * @return the value of tb_shop_auth_map.last_edit_time
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public Date getLastEditTime() {
        return lastEditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_shop_auth_map.last_edit_time
     *
     * @param lastEditTime the value for tb_shop_auth_map.last_edit_time
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setLastEditTime(Date lastEditTime) {
        this.lastEditTime = lastEditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_shop_auth_map.enable_status
     *
     * @return the value of tb_shop_auth_map.enable_status
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public Integer getEnableStatus() {
        return enableStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_shop_auth_map.enable_status
     *
     * @param enableStatus the value for tb_shop_auth_map.enable_status
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setEnableStatus(Integer enableStatus) {
        this.enableStatus = enableStatus;
    }
}