package com.scnu.o2o.domain;

import java.util.Date;

public class ShopCategory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shop_category.shop_category_id
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private Integer shopCategoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shop_category.shop_category_name
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private String shopCategoryName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shop_category.shop_category_desc
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private String shopCategoryDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shop_category.shop_category_img
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private String shopCategoryImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shop_category.priority
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private Integer priority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shop_category.create_time
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shop_category.last_edit_time
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private Date lastEditTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shop_category.parent_id
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private Integer parentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_shop_category.shop_category_id
     *
     * @return the value of tb_shop_category.shop_category_id
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public Integer getShopCategoryId() {
        return shopCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_shop_category.shop_category_id
     *
     * @param shopCategoryId the value for tb_shop_category.shop_category_id
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setShopCategoryId(Integer shopCategoryId) {
        this.shopCategoryId = shopCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_shop_category.shop_category_name
     *
     * @return the value of tb_shop_category.shop_category_name
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public String getShopCategoryName() {
        return shopCategoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_shop_category.shop_category_name
     *
     * @param shopCategoryName the value for tb_shop_category.shop_category_name
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setShopCategoryName(String shopCategoryName) {
        this.shopCategoryName = shopCategoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_shop_category.shop_category_desc
     *
     * @return the value of tb_shop_category.shop_category_desc
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public String getShopCategoryDesc() {
        return shopCategoryDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_shop_category.shop_category_desc
     *
     * @param shopCategoryDesc the value for tb_shop_category.shop_category_desc
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setShopCategoryDesc(String shopCategoryDesc) {
        this.shopCategoryDesc = shopCategoryDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_shop_category.shop_category_img
     *
     * @return the value of tb_shop_category.shop_category_img
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public String getShopCategoryImg() {
        return shopCategoryImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_shop_category.shop_category_img
     *
     * @param shopCategoryImg the value for tb_shop_category.shop_category_img
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setShopCategoryImg(String shopCategoryImg) {
        this.shopCategoryImg = shopCategoryImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_shop_category.priority
     *
     * @return the value of tb_shop_category.priority
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_shop_category.priority
     *
     * @param priority the value for tb_shop_category.priority
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_shop_category.create_time
     *
     * @return the value of tb_shop_category.create_time
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_shop_category.create_time
     *
     * @param createTime the value for tb_shop_category.create_time
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_shop_category.last_edit_time
     *
     * @return the value of tb_shop_category.last_edit_time
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public Date getLastEditTime() {
        return lastEditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_shop_category.last_edit_time
     *
     * @param lastEditTime the value for tb_shop_category.last_edit_time
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setLastEditTime(Date lastEditTime) {
        this.lastEditTime = lastEditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_shop_category.parent_id
     *
     * @return the value of tb_shop_category.parent_id
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_shop_category.parent_id
     *
     * @param parentId the value for tb_shop_category.parent_id
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }
}