package com.scnu.o2o.domain;

import java.util.Date;

public class UserProductMap {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_product_map.user_product_id
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private Integer userProductId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_product_map.user_id
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_product_map.product_id
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private Integer productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_product_map.shop_id
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private Integer shopId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_product_map.user_name
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_product_map.product_name
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_product_map.create_time
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_product_map.point
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private Integer point;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_product_map.user_product_id
     *
     * @return the value of tb_user_product_map.user_product_id
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public Integer getUserProductId() {
        return userProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_product_map.user_product_id
     *
     * @param userProductId the value for tb_user_product_map.user_product_id
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setUserProductId(Integer userProductId) {
        this.userProductId = userProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_product_map.user_id
     *
     * @return the value of tb_user_product_map.user_id
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_product_map.user_id
     *
     * @param userId the value for tb_user_product_map.user_id
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_product_map.product_id
     *
     * @return the value of tb_user_product_map.product_id
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_product_map.product_id
     *
     * @param productId the value for tb_user_product_map.product_id
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_product_map.shop_id
     *
     * @return the value of tb_user_product_map.shop_id
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public Integer getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_product_map.shop_id
     *
     * @param shopId the value for tb_user_product_map.shop_id
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setShopId(Integer shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_product_map.user_name
     *
     * @return the value of tb_user_product_map.user_name
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_product_map.user_name
     *
     * @param userName the value for tb_user_product_map.user_name
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_product_map.product_name
     *
     * @return the value of tb_user_product_map.product_name
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_product_map.product_name
     *
     * @param productName the value for tb_user_product_map.product_name
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setProductName(String productName) {
        this.productName = productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_product_map.create_time
     *
     * @return the value of tb_user_product_map.create_time
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_product_map.create_time
     *
     * @param createTime the value for tb_user_product_map.create_time
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_product_map.point
     *
     * @return the value of tb_user_product_map.point
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public Integer getPoint() {
        return point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_product_map.point
     *
     * @param point the value for tb_user_product_map.point
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setPoint(Integer point) {
        this.point = point;
    }
}