package com.scnu.o2o.domain;

import java.util.Date;

public class UserAwardMap {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_award_map.user_award_id
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private Integer userAwardId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_award_map.user_id
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_award_map.award_id
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private Integer awardId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_award_map.shop_id
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private Integer shopId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_award_map.user_name
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_award_map.award_name
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private String awardName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_award_map.expire_time
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private Date expireTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_award_map.create_time
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_award_map.used_status
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private Integer usedStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_award_map.point
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private Integer point;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_award_map.user_award_id
     *
     * @return the value of tb_user_award_map.user_award_id
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public Integer getUserAwardId() {
        return userAwardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_award_map.user_award_id
     *
     * @param userAwardId the value for tb_user_award_map.user_award_id
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setUserAwardId(Integer userAwardId) {
        this.userAwardId = userAwardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_award_map.user_id
     *
     * @return the value of tb_user_award_map.user_id
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_award_map.user_id
     *
     * @param userId the value for tb_user_award_map.user_id
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_award_map.award_id
     *
     * @return the value of tb_user_award_map.award_id
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public Integer getAwardId() {
        return awardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_award_map.award_id
     *
     * @param awardId the value for tb_user_award_map.award_id
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setAwardId(Integer awardId) {
        this.awardId = awardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_award_map.shop_id
     *
     * @return the value of tb_user_award_map.shop_id
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public Integer getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_award_map.shop_id
     *
     * @param shopId the value for tb_user_award_map.shop_id
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setShopId(Integer shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_award_map.user_name
     *
     * @return the value of tb_user_award_map.user_name
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_award_map.user_name
     *
     * @param userName the value for tb_user_award_map.user_name
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_award_map.award_name
     *
     * @return the value of tb_user_award_map.award_name
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public String getAwardName() {
        return awardName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_award_map.award_name
     *
     * @param awardName the value for tb_user_award_map.award_name
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setAwardName(String awardName) {
        this.awardName = awardName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_award_map.expire_time
     *
     * @return the value of tb_user_award_map.expire_time
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public Date getExpireTime() {
        return expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_award_map.expire_time
     *
     * @param expireTime the value for tb_user_award_map.expire_time
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setExpireTime(Date expireTime) {
        this.expireTime = expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_award_map.create_time
     *
     * @return the value of tb_user_award_map.create_time
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_award_map.create_time
     *
     * @param createTime the value for tb_user_award_map.create_time
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_award_map.used_status
     *
     * @return the value of tb_user_award_map.used_status
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public Integer getUsedStatus() {
        return usedStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_award_map.used_status
     *
     * @param usedStatus the value for tb_user_award_map.used_status
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setUsedStatus(Integer usedStatus) {
        this.usedStatus = usedStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_award_map.point
     *
     * @return the value of tb_user_award_map.point
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public Integer getPoint() {
        return point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_award_map.point
     *
     * @param point the value for tb_user_award_map.point
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setPoint(Integer point) {
        this.point = point;
    }
}