package com.scnu.o2o.domain;

import java.util.Date;

public class WechatAuth {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_wechat_auth.wechat_auth_id
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private Integer wechatAuthId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_wechat_auth.user_id
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_wechat_auth.open_id
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private String openId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_wechat_auth.create_time
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_wechat_auth.wechat_auth_id
     *
     * @return the value of tb_wechat_auth.wechat_auth_id
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public Integer getWechatAuthId() {
        return wechatAuthId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_wechat_auth.wechat_auth_id
     *
     * @param wechatAuthId the value for tb_wechat_auth.wechat_auth_id
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setWechatAuthId(Integer wechatAuthId) {
        this.wechatAuthId = wechatAuthId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_wechat_auth.user_id
     *
     * @return the value of tb_wechat_auth.user_id
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_wechat_auth.user_id
     *
     * @param userId the value for tb_wechat_auth.user_id
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_wechat_auth.open_id
     *
     * @return the value of tb_wechat_auth.open_id
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_wechat_auth.open_id
     *
     * @param openId the value for tb_wechat_auth.open_id
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setOpenId(String openId) {
        this.openId = openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_wechat_auth.create_time
     *
     * @return the value of tb_wechat_auth.create_time
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_wechat_auth.create_time
     *
     * @param createTime the value for tb_wechat_auth.create_time
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}