package com.scnu.o2o.dao;

import com.scnu.o2o.domain.HeadLine;
import com.scnu.o2o.domain.HeadLineExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HeadLineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_head_line
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    int countByExample(HeadLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_head_line
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    int deleteByExample(HeadLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_head_line
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    int deleteByPrimaryKey(Integer lineId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_head_line
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    int insert(HeadLine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_head_line
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    int insertSelective(HeadLine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_head_line
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    List<HeadLine> selectByExample(HeadLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_head_line
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    HeadLine selectByPrimaryKey(Integer lineId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_head_line
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    int updateByExampleSelective(@Param("record") HeadLine record, @Param("example") HeadLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_head_line
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    int updateByExample(@Param("record") HeadLine record, @Param("example") HeadLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_head_line
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    int updateByPrimaryKeySelective(HeadLine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_head_line
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    int updateByPrimaryKey(HeadLine record);
}