package com.scnu.o2o.dao;

import com.scnu.o2o.domain.LocalAuth;
import com.scnu.o2o.domain.LocalAuthExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LocalAuthMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_local_auth
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    int countByExample(LocalAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_local_auth
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    int deleteByExample(LocalAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_local_auth
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    int deleteByPrimaryKey(Integer localAuthId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_local_auth
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    int insert(LocalAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_local_auth
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    int insertSelective(LocalAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_local_auth
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    List<LocalAuth> selectByExample(LocalAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_local_auth
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    LocalAuth selectByPrimaryKey(Integer localAuthId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_local_auth
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    int updateByExampleSelective(@Param("record") LocalAuth record, @Param("example") LocalAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_local_auth
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    int updateByExample(@Param("record") LocalAuth record, @Param("example") LocalAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_local_auth
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    int updateByPrimaryKeySelective(LocalAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_local_auth
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    int updateByPrimaryKey(LocalAuth record);
}