package com.scnu.o2o.dao;

import com.scnu.o2o.domain.PersonInfo;
import com.scnu.o2o.domain.PersonInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PersonInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_person_info
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    int countByExample(PersonInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_person_info
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    int deleteByExample(PersonInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_person_info
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_person_info
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    int insert(PersonInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_person_info
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    int insertSelective(PersonInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_person_info
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    List<PersonInfo> selectByExample(PersonInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_person_info
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    PersonInfo selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_person_info
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    int updateByExampleSelective(@Param("record") PersonInfo record, @Param("example") PersonInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_person_info
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    int updateByExample(@Param("record") PersonInfo record, @Param("example") PersonInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_person_info
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    int updateByPrimaryKeySelective(PersonInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_person_info
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    int updateByPrimaryKey(PersonInfo record);
}