package com.scnu.o2o.dao;

import com.scnu.o2o.domain.PhoneAuth;
import com.scnu.o2o.domain.PhoneAuthExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PhoneAuthMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_phone_auth
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    int countByExample(PhoneAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_phone_auth
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    int deleteByExample(PhoneAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_phone_auth
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    int deleteByPrimaryKey(Integer phoneAuthId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_phone_auth
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    int insert(PhoneAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_phone_auth
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    int insertSelective(PhoneAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_phone_auth
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    List<PhoneAuth> selectByExample(PhoneAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_phone_auth
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    PhoneAuth selectByPrimaryKey(Integer phoneAuthId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_phone_auth
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    int updateByExampleSelective(@Param("record") PhoneAuth record, @Param("example") PhoneAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_phone_auth
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    int updateByExample(@Param("record") PhoneAuth record, @Param("example") PhoneAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_phone_auth
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    int updateByPrimaryKeySelective(PhoneAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_phone_auth
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    int updateByPrimaryKey(PhoneAuth record);
}