package com.scnu.o2o.dao;

import com.scnu.o2o.domain.ProductImg;
import com.scnu.o2o.domain.ProductImgExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductImgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product_img
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    int countByExample(ProductImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product_img
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    int deleteByExample(ProductImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product_img
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    int deleteByPrimaryKey(Integer productImgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product_img
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    int insert(ProductImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product_img
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    int insertSelective(ProductImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product_img
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    List<ProductImg> selectByExample(ProductImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product_img
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    ProductImg selectByPrimaryKey(Integer productImgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product_img
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    int updateByExampleSelective(@Param("record") ProductImg record, @Param("example") ProductImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product_img
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    int updateByExample(@Param("record") ProductImg record, @Param("example") ProductImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product_img
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    int updateByPrimaryKeySelective(ProductImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product_img
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    int updateByPrimaryKey(ProductImg record);
}