package com.scnu.o2o.dao;

import com.scnu.o2o.domain.ShopCategory;
import com.scnu.o2o.domain.ShopCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShopCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_shop_category
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    int countByExample(ShopCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_shop_category
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    int deleteByExample(ShopCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_shop_category
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    int deleteByPrimaryKey(Integer shopCategoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_shop_category
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    int insert(ShopCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_shop_category
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    int insertSelective(ShopCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_shop_category
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    List<ShopCategory> selectByExample(ShopCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_shop_category
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    ShopCategory selectByPrimaryKey(Integer shopCategoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_shop_category
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    int updateByExampleSelective(@Param("record") ShopCategory record, @Param("example") ShopCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_shop_category
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    int updateByExample(@Param("record") ShopCategory record, @Param("example") ShopCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_shop_category
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    int updateByPrimaryKeySelective(ShopCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_shop_category
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    int updateByPrimaryKey(ShopCategory record);
}