package com.scnu.o2o.dao;

import com.scnu.o2o.domain.ShopAuthMap;
import com.scnu.o2o.domain.ShopAuthMapExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShopAuthMapMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_shop_auth_map
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    int countByExample(ShopAuthMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_shop_auth_map
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    int deleteByExample(ShopAuthMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_shop_auth_map
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    int deleteByPrimaryKey(Integer shopAuthId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_shop_auth_map
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    int insert(ShopAuthMap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_shop_auth_map
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    int insertSelective(ShopAuthMap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_shop_auth_map
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    List<ShopAuthMap> selectByExample(ShopAuthMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_shop_auth_map
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    ShopAuthMap selectByPrimaryKey(Integer shopAuthId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_shop_auth_map
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    int updateByExampleSelective(@Param("record") ShopAuthMap record, @Param("example") ShopAuthMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_shop_auth_map
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    int updateByExample(@Param("record") ShopAuthMap record, @Param("example") ShopAuthMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_shop_auth_map
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    int updateByPrimaryKeySelective(ShopAuthMap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_shop_auth_map
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    int updateByPrimaryKey(ShopAuthMap record);
}