package com.scnu.o2o.dao;

import com.scnu.o2o.domain.UserAwardMap;
import com.scnu.o2o.domain.UserAwardMapExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserAwardMapMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_award_map
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    int countByExample(UserAwardMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_award_map
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    int deleteByExample(UserAwardMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_award_map
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    int deleteByPrimaryKey(Integer userAwardId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_award_map
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    int insert(UserAwardMap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_award_map
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    int insertSelective(UserAwardMap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_award_map
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    List<UserAwardMap> selectByExample(UserAwardMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_award_map
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    UserAwardMap selectByPrimaryKey(Integer userAwardId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_award_map
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    int updateByExampleSelective(@Param("record") UserAwardMap record, @Param("example") UserAwardMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_award_map
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    int updateByExample(@Param("record") UserAwardMap record, @Param("example") UserAwardMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_award_map
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    int updateByPrimaryKeySelective(UserAwardMap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_award_map
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    int updateByPrimaryKey(UserAwardMap record);
}