package com.scnu.o2o.dao;

import com.scnu.o2o.domain.UserProductMap;
import com.scnu.o2o.domain.UserProductMapExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserProductMapMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_product_map
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    int countByExample(UserProductMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_product_map
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    int deleteByExample(UserProductMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_product_map
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    int deleteByPrimaryKey(Integer userProductId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_product_map
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    int insert(UserProductMap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_product_map
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    int insertSelective(UserProductMap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_product_map
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    List<UserProductMap> selectByExample(UserProductMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_product_map
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    UserProductMap selectByPrimaryKey(Integer userProductId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_product_map
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    int updateByExampleSelective(@Param("record") UserProductMap record, @Param("example") UserProductMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_product_map
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    int updateByExample(@Param("record") UserProductMap record, @Param("example") UserProductMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_product_map
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    int updateByPrimaryKeySelective(UserProductMap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_product_map
     *
     * @mbggenerated Thu Oct 04 14:40:21 CST 2018
     */
    int updateByPrimaryKey(UserProductMap record);
}